langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASHSCOPE_API_KEY:sk-key}
      model-name: qwen-plus
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: ${DASHSCOPE_API_KEY:sk-key}
      model-name: qwq-plus-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
#  community:
#    dashscope:
#      api-key: ${DASHSCOPE_API_KEY:sk-key}
#      model-name: qwq-plus-latest
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      log-requests: true
#      log-responses: true
#      temperature: 0.7
#      max-tokens: 4096
#
logging:
  level:
    dev:
      langchain4j: debug
    org:
      springframework:
        ai: debug
        web:
          client: debug
    io:
      modelcontextprotocol:
        client: debug
        spec: debug
#
server:
  port: 8080
  undertow:
    threads:
      io: 4       # I/O线程数 (建议设置为CPU核心数)
      worker: 40  # 工作线程数 (默认计算公式：CPU核心数 * 8)
    buffer-size: 1024  # 缓冲区大小(bytes)
    direct-buffers: true  # 使用直接内存
    http2: true
    max-parameters: 1000    # 最大请求参数数量
    max-headers: 200        # 最大header数量
    max-cookies: 200        # 最大cookie数量
    no-request-timeout: 1000  # 请求超时(ms)
    accesslog:
      dir: ./build/logs
      prefix: access_log
      suffix: log
      pattern: '%h %l %u %t "%r" %s %b'
#
spring.datasource:
    url: jdbc:h2:mem:proposal-agent.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
#
spring.jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 10
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

#
spring.mvc:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600